<?php

namespace app\models\forms;

use app\models\User;
use Yii;
use yii\base\Model;
use app\utils\D;

/**
 * Signup form
 */
class WithdrawalForm extends Model
{

    public $value;

    public function init()
    {
        $this->value = Yii::$app->user->identity->billing;
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['value', 'required'],
            ['value', 'integer','max' => Yii::$app->user->identity->billing,'min' => 50],
        ];
    }

    public function attributeLabels()
    {
        return [
            'value' => Yii::t('app','value'),
        ];
    }

    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     */

}